name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
https://github.com/ittat-store/nutria
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
      ls
      ./jackady update-prebuilts
