name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        ./jackady update-prebuilts
        mkdir out
        cd builder
        chmod +x ./install.sh
        NUTRIA_APPS_ROOT=/home/runner/work/nutria/nutria/apps/  ./install.sh ../out
        
    - name: Upload Artifact
      continue-on-error: true
      uses: actions/upload-artifact@master
      with:
        name: apps.zip
        path: /home/runner/work/nutria/nutria/out

